INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-02', 'Fevereiro a Junho 2023 - MDS', 'Fevereiro a Junho 2023 - FDS');
INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-03', 'Fevereiro a Junho 2023 - MDS', 'Fevereiro a Junho 2023 - FDS');
INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-04', 'Fevereiro a Junho 2023 - MDS', 'Fevereiro a Junho 2023 - FDS');
INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-05', 'Fevereiro a Junho 2023 - MDS', 'Fevereiro a Junho 2023 - FDS');
INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-06', 'Fevereiro a Junho 2023 - MDS', 'Fevereiro a Junho 2023 - FDS');
INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-07', 'Julho 2023 - MDS', 'Julho 2023 - FDS');
INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-08', 'Agosto a Setembro 2023 - MDS', 'Agosto a Setembro 2023 - FDS');
INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-09', 'Agosto a Setembro 2023 - MDS', 'Agosto a Setembro 2023 - FDS');
INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-10', 'Outubro a Dezembro 2023 - MDS', 'Outubro a Dezembro 2023 - FDS');
INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-11', 'Outubro a Dezembro 2023 - MDS', 'Outubro a Dezembro 2023 - FDS');
INSERT INTO public.common_dates (date, tariff_to_midweek_id, tariff_to_weekend_id) VALUES ('2023-12', 'Outubro a Dezembro 2023 - MDS', 'Outubro a Dezembro 2023 - FDS');
