INSERT INTO public.requirements (name, price, active) VALUES ('check-in às 12h sem apto', 0, true);
INSERT INTO public.requirements (name, price, active) VALUES ('check-in às 10h com apto', 0, true);
INSERT INTO public.requirements (name, price, active) VALUES ('decoração romântica I', 295, true);
INSERT INTO public.requirements (name, price, active) VALUES ('decoração romântica II', 325, true);
INSERT INTO public.requirements (name, price, active) VALUES ('decoração romântica III', 435, true);
INSERT INTO public.requirements (name, price, active) VALUES ('decoração romântica IV', 575, true);
INSERT INTO public.requirements (name, price, active) VALUES ('observação C.E.U (inteira)', 56, true);
INSERT INTO public.requirements (name, price, active) VALUES ('observação C.E.U (meia)', 35, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Eco A. - Rafting', 148, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Eco A. - Mini Rafting', 99, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Eco A. - Rafting Pet', 99, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Eco A. - Rafting noturno', 158, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Eco A. - KR', 190, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Eco A. - Duck', 200, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Eco A. - Tirolesa do Benjamin', 120, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Rafting', 138, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Bote elite', 158, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Rafting noturno', 158, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Duck radical', 199, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Boia cross', 89, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Rafting KIDS', 89, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Rafting PET', 89, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Super tirolesa', 150, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Tirolesa mega tour', 119, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Trilha cristal', 99, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Tirolesa voo das cachoeiras', 99, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Canonismo cassorova', 279, true);
INSERT INTO public.requirements (name, price, active) VALUES ('Território - Day use - Eco parque jacaré', 70, true);
