INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('Fevereiro a Junho 2023 - MDS', '385', true, 8, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('Fevereiro a Junho 2023 - FDS', '386', true, 9, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('Julho 2023 - MDS', '390', true, 10, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('Julho 2023 - FDS', '391', true, 11, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('Agosto a Setembro 2023 - MDS', '397', true, 12, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('Agosto a Setembro 2023 - FDS', '396', true, 13, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('Outubro a Dezembro 2023 - MDS', '398', true, 16, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('Outubro a Dezembro 2023 - FDS', '399', true, 17, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('NATAL 2023', '402', true, 19, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('N SRA APARECIDA 2023', '395', true, 15, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('CONSC. NEGRA 2023', '405', true, 18, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('INDEPENDÊNCIA 2023', '394', true, 14, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('REVEILLON 2023', '403', true, 20, 1);
INSERT INTO public.tariffs (name, product_pipe, active, order_id, food_id) VALUES ('CORPUS CHRISTI 2023', '393', true, 7, 1);
